version: '3.8'

services:
  rstudio:
    image: rocker/rstudio:latest
    container_name: rstudio-server
    environment:
      - USER=admin2
      - PASSWORD=redhat
    ports:
      - "8787:8787"
    volumes:
      - tmpfs:/home/rstudio
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: AdventureWorks
      MYSQL_USER: admin2
      MYSQL_PASSWORD: redhat
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/AdventureWorks.sql:/docker-entrypoint-initdb.d/AdventureWorks.sql
    restart: always

volumes:
  tmpfs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  mysql-data:
    external: false
